### ISSUE TITLE
Application crash after sometime,  when more then 3-4 users are joined a room. 

### ISSUE THREAD

**Issue by pintukumarpatil** [ethand91/mediasoup-android-sample#3] opened 2019-11-21 14:03 UTC
Hello @ethand91 

Application crash after joining in a room by more then 3-4 users.

Scenario: Run application in a mobile, After that i am opening url into more then three browser tab. 

2019-11-21 19:14:47.857 14064-14163/com.example.mediasoupandroidsample E/org.webrtc.Logging: CameraStatistics: Camera freezed.
2019-11-21 19:15:00.667 14064-14163/com.example.mediasoupandroidsample E/org.webrtc.Logging: Camera2Session: Error: Camera device has encountered a fatal error.
2019-11-21 19:15:00.668 14064-14163/com.example.mediasoupandroidsample E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2406)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1104)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
        at org.webrtc.Camera2Session.stopInternal(Camera2Session.java:380)
        at org.webrtc.Camera2Session.reportError(Camera2Session.java:401)
        at org.webrtc.Camera2Session.access$600(Camera2Session.java:35)
        at org.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:114)
        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:1900)
        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
        at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:258)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-11-21 19:15:01.703 14064-14163/com.example.mediasoupandroidsample E/MediaCapturer: onCameraError s=Camera device has encountered a fatal error.

**Comment by ethand91** [comment] 2019-11-21 14:13
Hello @pintukumarpatil 
The sample application does not yet support multiple remotes...
I've added it to the TODO.

**Comment by pintukumarpatil** [comment] 2019-11-21 14:25
Hello @ethand91 
I will look into this.....Thanks

**Comment by pintukumarpatil** [comment] 2019-11-22 12:35
Hello @ethand91 
Application also crashing after joining in a room by 2 users(1-mobile and 1-web user).
After approx 30 min app crash with same above logs. 
I think, it's related to CameraVideoCapturer not with multiple remote tracks.
Emulator : Google Pixel-3

**Comment by ethand91** [comment] 2019-11-24 11:28
Hello @pintukumarpatil 
Thanks for the information! I'll see if I can  reproduce the issue on my end.

**Comment by ethand91** [comment] 2019-11-25 01:43
Hi @pintukumarpatil 
I couldn't produce this issue on an actual device.
It may be an emulator only problem? Could you please see if you could reproduce it on your end with an actual device?

**Comment by pintukumarpatil** [comment] 2019-11-26 12:27
> Hi @pintukumarpatil
> I couldn't produce this issue on an actual device.
> It may be an emulator only problem? Could you please see if you could reproduce it on your end with an actual device?

Yes @ethand91 i did check in actual device its working fine, error occurring only in emulator.

**Comment by ethand91** [comment] 2019-11-27 01:37
@pintukumarpatil 
OK, could you tell me what version of android os the emulator is running?
Also what camera is the android emulator using? Is it an actual camera or is it an emulated one?

The exception seems to be about camera access/query, if you are using an actual camera could you try it using different camera?

**Comment by pintukumarpatil** [comment] 2019-11-27 08:07
Hello @ethand91 
Google Pixel-2(pie os) emulator working good with external web cam.
Problem with only emulated camera with Google Pixel-2( pie os).
It's not a big issue so we can ignore for now.

**Comment by ethand91** [comment] 2019-11-27 08:52
@pintukumarpatil 
The emulated camera might work with Camera1Enumerator?
Not a major issue so I'll close it for now.

**Closed as completed by ethand91** 2019-11-27 08:52 UTC
Labels: bug
